# docker compose up --build

version: "3"

# These are the services that constitute this Docker Compose "stack".
services:

  # The NMDC EDGE web app (both client and server).
  webapp:
    build:
      context: .
      dockerfile: webapp.Dockerfile
      args:
        API_HOST: localhost
        API_PORT: 8000
    environment:
      MONGO_URI: mongodb://mongo:27017/nmdcedge
    ports: [ "8000:8000" ]
    depends_on: [ mongo ]

  # A MongoDB server (see: https://hub.docker.com/_/mongo).
  mongo:
    image: mongo
    restart: unless-stopped
    ports: [ "27017:27017" ]
