"""
Test that the workflow inputs generated by the Cromwell job runner and the WDLs
specified in the workflow configuration are valid and can be submitted to a job runner.
"""
import json
import logging
import os
import pytest

from nmdc_automation.workflow_automation.wfutils import WorkflowStateManager

logging_level = os.getenv("NMDC_LOG_LEVEL", logging.INFO)
logging.basicConfig(
    level=logging_level, format="%(asctime)s %(levelname)s: %(message)s"
)

logger = logging.getLogger(__name__)

@pytest.mark.integration
@pytest.mark.parametrize(
    "fixture", ["rqc_workflow_state.json", "meta_assembly_workflow_state.json",
                "read_based_analysis_workflow_state.json", "mags_workflow_state.json", "annotation_workflow_state.json"]
    )
def test_workflow_inputs_and_wdl(site_config, fixtures_dir, fixture):
    """
    Test the the
    """