# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "Refactor_fgi_file_staging_unit_tests" ]
  pull_request:
    branches: [ "Refactor_fgi_file_staging_unit_tests" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: |
        poetry install
  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: --health-cmd "mongo --version" --health-interval 10s --health-timeout 5s --health-retries 12
    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python 3.9
#      uses: actions/setup-python@v3
#      with:
#        python-version: "3.9"
#    - name: Install Poetry
#      uses: snok/install-poetry@v1
#    - name: Install dependencies
#      run: |
#        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest

